### ISSUE TITLE
layout issue in Chrome - Windows

### ISSUE THREAD

**Issue by andremarcondesteixeira** [rFramework/rFramework#1]
![image](https://user-images.githubusercontent.com/4294962/33087082-b2941ed0-ced0-11e7-9fe7-b2a8ef27a1ec.png)

Chrome version: Version 62.0.3202.94 (Official Build) (64-bit)
Windows 10

**Comment by andremarcondesteixeira** [comment]
![image](https://user-images.githubusercontent.com/4294962/33087330-5c28bf28-ced1-11e7-9535-598cb8733868.png)

**Comment by andremarcondesteixeira** [comment]
![image](https://user-images.githubusercontent.com/4294962/33087349-7221e3fe-ced1-11e7-9b60-948706767737.png)

**Comment by andremarcondesteixeira** [comment]
I think the twitter board Is a little too big ;) but that just my opinion, though, your project looks awesome!

**Comment by andremarcondesteixeira** [comment]
![image](https://user-images.githubusercontent.com/4294962/33087446-c901cedc-ced1-11e7-85b0-4c39f6a8451b.png)

the social buttons are not aligned

**Comment by andremarcondesteixeira** [comment]
you could put the GitHub stars button alongside the other social buttons as well ;)

**Comment by andremarcondesteixeira** [comment]
when you click the "Features" navigation link, the text "Features" appears a little bit hidden

![image](https://user-images.githubusercontent.com/4294962/33087534-0cbc84a0-ced2-11e7-9696-dc272f6def7e.png)

**Comment by lucabtz** [comment]
Still a problem, even on Safari (yeah don't ask y I'm using a Mac). I'm no expert in front end, but maybe fix z-index?
